name: Push to S3

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AKIAU6GD27TWVNHMNBOT }}
          aws-secret-access-key: ${{ secrets.ErQ9XWFZ0NClUxdvQw59EOcyXkVKGxvFAr9nu9Qz }}
          aws-region: us-east-1
      - name: Sync files to S3 bucket
        run: |
          aws s3 sync s3://ctownscloudresumebucket --delete
